version: '3'

services:
  web:
    container_name: Breizhsport-Utilisateur
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - .:/app
    networks:
      - breizhsport-produit_breizhsport-network

networks:
  breizhsport-produit_breizhsport-network:
    external: true
