name: Deploy automatically

on:
  push:
    tags:
      - '*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build Docker Image
        run: docker build -t electrix67/breizhsport-utilisateur-api:${{ github.ref_name }} .

      - name: Login to Docker Registry
        run: echo "${{ secrets.DOCKER_REGISTRY_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" --password-stdin

      - name: Push Docker Image
        run: docker push electrix67/breizhsport-utilisateur-api:${{ github.ref_name }}
