name: Deploy to VM with VPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install VPN client
      run: |
        sudo apt update
        sudo apt install -y openconnect 

    - name: Connect to VPN
      run: |
        echo "${{ secrets.VPN_PASSWORD }}" | sudo openconnect -u ${{ secrets.VPN_USERNAME }} --passwd-on-stdin strasbourg-vpn.numerilab-cesi.fr


    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.azert }}

    - name: Deploy to VM
      run: |
        # Connect to VM and deploy using Docker Compose
        ssh root@172.16.47.100 "cd ./ && docker-compose up -d"
