name: Deploy to VM with VPN

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install VPN client
      run: |
        sudo apt update
        sudo apt install -y openconnect 
    
    - name: Connect to VPN
      run: sudo openconnect -u ${{ secrets.VPN_USERNAME }} --passwd-on-stdin strasbourg-vpn.numerilab-cesi.fr --no-cert-check --debug <<<"${{ secrets.VPN_PASSWORD }}"

    - name: Get Server Certificate Fingerprint
      run: |
        SSH_PRIVATE_KEY="${{ secrets.SSH_KEY }}"
        echo "$SSH_PRIVATE_KEY"
        echo "${{ secrets.SSH_KEY }}"
        SERVER_CERT_FINGERPRINT=$(echo "$SSH_PRIVATE_KEY" | ssh -i - root@172.16.47.100 "openssl s_client -connect strasbourg-vpn.numerilab-cesi.fr:443 2>/dev/null | openssl x509 -noout -fingerprint | awk -F= '{print \$2}' | tr -d ':'")
        echo "Server Certificate Fingerprint: $SERVER_CERT_FINGERPRINT"
        echo "::set-output name=SERVER_CERT_FINGERPRINT::$SERVER_CERT_FINGERPRINT"

    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.azert }}

    - name: Deploy to VM
      run: |
        # Connect to VM and deploy using Docker Compose
        ssh root@172.16.47.100 "cd ./ && docker-compose up -d"
