name: CI Pipeline

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install VPN client
        run: |
          sudo apt update
          sudo apt install -y openconnect 
    
      - name: Connect to VPN
        run: 
          echo f@rPvtg4 | sudo openconnect -u nlanotte --passwd-on-stdin strasbourg-vpn.numerilab-cesi.fr &
          
      - name: Install Dependencies
        run: npm ci

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }} 

      - name: Snyk Test
        run: snyk test || true

      - name: Run Jest Tests
        run: npm test

      - name: Snyk Monitor
        run: snyk monitor 