name: CI Pipeline

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: Install Dependencies
        run: npm install

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Install Jest CLI
        run: npm install jest

      - name: Snyk Auth
        run: snyk auth ${{ secrets.SNYK_TOKEN }} 

      - name: Run Jest Tests
        run: npm test

      - name: Snyk Test
        run: snyk test  

      - name: Snyk Monitor
        run: snyk monitor 